# Project information 
site_name: VNCTF Wiki
site_author: VNCTF Team
site_url: 

# Repository
repo_name: 'vnctfwiki/VNCTF-Wiki'
repo_url: 'https://github.com/vnctfwiki/VNCTF-Wiki'

# Copyright 
# Contents
nav:
  - Home:
    - Introduction: 
    - Usage:  
    - Contribute: 
    - Chat: 
  - Miscellaneous: 
  - Cryptography:
  - Operating System: 
  - Web:
  - Pwnable: 
  - Reverse Engineering: 
  - Hardware: 
  - Blockchain: 

# Themes
theme: 
  name: material
  palette:
    primary: indigo
    accent: red
    scheme: preference
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share

# Extensions
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js